"""Audit public inactive candidate packets without reading protected answer stores.

Hashes bind authored files only. Review/release gates stay unresolved; this report
does not approve a candidate, judge teaching quality or change course maturity.
"""

import argparse
import hashlib
import json
from pathlib import Path

FORBIDDEN = {"answer", "solution_spec", "field_specs", "feedback", "rubric", "checks"}


def keys(value):
    if isinstance(value, dict):
        for key, child in value.items():
            yield key
            yield from keys(child)
    elif isinstance(value, list):
        for child in value:
            yield from keys(child)


def digest(course, relative):
    path = (course / relative).resolve()
    if not path.is_relative_to(course.resolve()) or not path.is_file():
        raise ValueError(f"Public artifact is missing or escapes course: {relative}")
    return hashlib.sha256(path.read_bytes()).hexdigest()


def audit(root):
    packages = []
    for manifest in sorted((root / "content/courses").glob("*/course.json")):
        course = manifest.parent
        m = json.loads(manifest.read_text(encoding="utf-8"))
        known = {o["id"] for o in m["lesson_objectives"]}
        versions = {entry["version"] for entry in m["history"]}
        candidates = []
        for path in sorted((course / "assessment-specs").glob("*-candidate.json")):
            c = json.loads(path.read_text(encoding="utf-8"))
            if c["course_id"] != m["id"] or c["content_version"] not in versions:
                raise ValueError(f"Candidate course/version mapping is invalid: {path.name}")
            if c["state"] != "inactive-review-candidate":
                raise ValueError(f"Audit supports inactive drafts only: {path.name}")
            if c["candidate_id"] in {a["id"] for a in m["assessments"]}:
                raise ValueError(f"Inactive candidate is enrolled in assessment policy: {path.name}")
            if not set(c["objective_ids"]) <= known:
                raise ValueError(f"Unknown candidate objective: {path.name}")
            q = c["questions"]
            variants = c.get("variant_questions", {})
            if FORBIDDEN.intersection(keys([q, variants])):
                raise ValueError(f"Protected grader fields appear in public DTOs: {path.name}")
            if len({v["id"] for v in q}) != len(q) or sum(v["points"] for v in q) != c["points"]:
                raise ValueError(f"Candidate question IDs or point total are invalid: {path.name}")
            if variants and set(variants) != {v["id"] for v in q}:
                raise ValueError(f"Variant DTO mapping is invalid: {path.name}")
            files = [c["instruction_path"], c["dataset_path"], *c.get("additional_dataset_paths", [])]
            files.extend(c[k] for k in ("generator_path", "human_portfolio_path") if k in c)
            hashes = {relative: digest(course, relative) for relative in files}
            for relative, expected in c.get("prerequisite_sha256", {}).items():
                actual = digest(course, relative)
                if actual != expected:
                    raise ValueError(f"Candidate prerequisite digest changed: {path.name}: {relative}")
                hashes[relative] = actual
            candidates.append({
                "id": c["candidate_id"], "version": c["content_version"], "state": c["state"],
                "questions": len(q), "points": c["points"], "distinct_objectives": len(set(c["objective_ids"])),
                "authored_forms": 2 if variants else 1, "declared_review_status": c["review"]["status"],
                "unresolved_activation_gates": list(c["activation_gates"]),
                "metadata_sha256": hashlib.sha256(path.read_bytes()).hexdigest(), "artifact_sha256": hashes,
            })
        packages.append({
            "course": m["id"], "version": m["version"], "maturity": m["maturity"],
            "declared_review_status": m["review"]["status"], "grading_mode": m["grading_policy"]["mode"],
            "manifest_sha256": hashlib.sha256(manifest.read_bytes()).hexdigest(), "candidates": candidates,
        })
    return {"schema_version": "1.0", "evidence_scope": "public-authoring-artifact-audit-only", "packages": packages}


def render(report):
    lines = [
        "# Public assessment candidate audit", "",
        "Generated by `python tools/assessment_candidates.py`. This checks public authoring artifacts and hashes;",
        "it never opens a protected key store. It does not establish numerical/scientific correctness, qualified review,",
        "workload, protected variant delivery, human portfolio grading or release readiness. All listed activation gates",
        "remain unresolved by this audit, even if a candidate declares review. Maturity and grading policy are declarations.",
        "No course or candidate is activated by this command. `--check` detects report drift; `--json` emits file hashes.", "",
        "| Package | Version | Maturity | Declared review | Grading | Inactive drafts |",
        "| --- | --- | --- | --- | --- | ---: |",
    ]
    for p in report["packages"]:
        lines.append(f'| {p["course"]} | {p["version"]} | {p["maturity"]} | {p["declared_review_status"]} | {p["grading_mode"]} | {len(p["candidates"])} |')
    lines.extend(["", "## Candidate inventory", "", "Forms and point counts describe authored machine-check subsets, not complete assessment evidence or course grades.", ""])
    for p in report["packages"]:
        for c in p["candidates"]:
            lines.extend([
                f'### {c["id"]}', "",
                f'Authored version {c["version"]}; {c["questions"]} cases/items; {c["points"]:g} machine-check points; {c["authored_forms"]} fixed form(s); {c["distinct_objectives"]} distinct objective links. Declared review: {c["declared_review_status"]}.', "",
                f'Metadata SHA-256: `{c["metadata_sha256"]}`.', "",
                "Unresolved gates: " + ", ".join(c["unresolved_activation_gates"]) + ".", "",
                "| Public artifact | SHA-256 |", "| --- | --- |",
            ])
            for name, sha in sorted(c["artifact_sha256"].items()):
                lines.append(f'| {p["course"]}/{name} | `{sha}` |')
            lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[1])
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--write", type=Path)
    mode.add_argument("--check", type=Path)
    mode.add_argument("--json", action="store_true")
    args = parser.parse_args()
    try:
        report = audit(args.root)
        text = render(report)
    except (ValueError, KeyError, TypeError, OSError) as exc:
        parser.exit(1, f"Candidate audit failed: {exc}\n")
    if args.write:
        args.write.write_text(text, encoding="utf-8")
    elif args.check:
        if not args.check.is_file() or args.check.read_text(encoding="utf-8") != text:
            parser.exit(1, "Candidate report is stale; regenerate it with --write.\n")
    else:
        print(json.dumps(report, indent=2) if args.json else text, end="\n" if args.json else "")


if __name__ == "__main__":
    main()
