#!/usr/bin/env python3
"""Measured gap report: which objectives and course outcomes have no assessment mapping, practice item or link.

Reads only the committed course packages. It does not grade, does not judge teaching quality and
does not change any maturity label. A listed gap is a work item, not a defect claim; an empty list
is not evidence of comprehensive coverage.

    python tools/objective_coverage.py            # print the Markdown report
    python tools/objective_coverage.py --check docs/COURSE_GAP_REPORT.md   # exit 1 if the file is stale
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
COURSES = ROOT / "content" / "courses"


def load(path: Path):
    return json.loads(path.read_text(encoding="utf-8"))


def course_rows():
    for manifest_path in sorted(COURSES.glob("*/course.json")):
        course = load(manifest_path)
        base = manifest_path.parent
        objectives = [item["id"] for item in course.get("lesson_objectives", [])]
        lessons = [lesson for module in course.get("modules", []) for lesson in module.get("lessons", [])]
        mapped = {oid for a in course.get("assessments", []) for oid in a.get("objective_ids", [])}
        questions = {}
        for bank in sorted((base / "question-banks").glob("practice*.json")):
            for question in load(bank).get("questions", []):
                questions[question["id"]] = question
        practised = {oid for q in questions.values() for oid in q.get("objective_ids", [])}
        outcomes = [item["id"] for item in course.get("outcomes", [])]
        linked = {oid for item in course.get("lesson_objectives", []) for oid in item.get("course_outcome_ids", [])}
        cards = 0
        cards_path = base / "question-banks" / "retrieval-cards.json"
        if cards_path.is_file():
            cards = len(load(cards_path).get("cards", []))
        yield {
            "id": course["id"], "maturity": course.get("maturity"), "lessons": len(lessons),
            "objectives": len(objectives), "questions": len(questions), "cards": cards,
            "unmapped": sorted(set(objectives) - mapped), "no_item": sorted(set(objectives) - practised),
            "assessments": len(course.get("assessments", [])),
            "outcomes": len(outcomes), "outcomes_unlinked": sorted(set(outcomes) - linked),
            "outcomes_unlisted": sorted(set(outcomes) - mapped),
            "objectives_no_outcome": sorted(
                item["id"] for item in course.get("lesson_objectives", []) if not item.get("course_outcome_ids")
            ),
        }


def render(rows) -> str:
    lines = [
        "# Course gap report",
        "",
        "Generated by `python tools/objective_coverage.py`; `--check` fails when this file is stale. It counts what is in",
        "the committed packages. It does not assess teaching quality, and an empty gap list is not evidence of",
        "comprehensive coverage. Every package is still `partial` and unreviewed.",
        "",
        "| Package | Maturity | Lessons | Objectives | Practice items | Cards | Objectives with no assessment mapping | Objectives with no practice item | Objectives linked to no outcome | Course outcomes | Outcomes no lesson objective links to | Outcomes no assessment lists |",
        "|---|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|",
    ]
    for r in rows:
        lines.append(f"| {r['id']} | {r['maturity']} | {r['lessons']} | {r['objectives']} | {r['questions']} | "
                     f"{r['cards']} | {len(r['unmapped'])} | {len(r['no_item'])} | {len(r['objectives_no_outcome'])} | "
                     f"{r['outcomes']} | {len(r['outcomes_unlinked'])} | {len(r['outcomes_unlisted'])} |")
    total = lambda key: sum(len(r[key]) for r in rows)  # noqa: E731
    lines += ["", f"Totals: {len(rows)} packages, {sum(r['lessons'] for r in rows)} lessons, "
              f"{sum(r['objectives'] for r in rows)} objectives, {sum(r['questions'] for r in rows)} practice items, "
              f"{total('unmapped')} lesson objectives with no assessment mapping, {total('no_item')} with no practice item, "
              f"{total('objectives_no_outcome')} linked to no course outcome; "
              f"{total('outcomes_unlinked')} of {sum(r['outcomes'] for r in rows)} course outcomes that no lesson objective links to, "
              f"{total('outcomes_unlisted')} that no assessment lists.",
              "",
              "Each assessment with items lists the course outcomes its own items assess (item, then its tagged lesson objective,",
              "then that objective's outcome links), and `tools/validate_content.py` rejects an outcome that none of the",
              "assessment's items assesses. A listed outcome means at least one item touches it, not that it is assessed in depth.",
              "Objectives linked to no outcome are mostly those of the short prototype units; linking them is a judgement for a",
              "subject-matter reviewer, so this report lists them rather than doing it.", ""]
    for r in rows:
        if r["unmapped"] or r["no_item"] or r["outcomes_unlinked"] or r["outcomes_unlisted"] or r["objectives_no_outcome"]:
            lines.append(f"## {r['id']}")
            lines.append("")
            if r["unmapped"]:
                lines.append("No assessment mapping: " + ", ".join(f"`{o}`" for o in r["unmapped"]))
                lines.append("")
            if r["outcomes_unlinked"]:
                lines.append("Outcomes with no linking lesson objective: " + ", ".join(f"`{o}`" for o in r["outcomes_unlinked"]))
                lines.append("")
            if r["no_item"]:
                lines.append("No practice item: " + ", ".join(f"`{o}`" for o in r["no_item"]))
                lines.append("")
            if r["outcomes_unlisted"]:
                lines.append("Outcomes no assessment lists: " + ", ".join(f"`{o}`" for o in r["outcomes_unlisted"]))
                lines.append("")
            if r["objectives_no_outcome"]:
                lines.append("Objectives linked to no outcome: " + ", ".join(f"`{o}`" for o in r["objectives_no_outcome"]))
                lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", metavar="FILE")
    args = parser.parse_args(argv)
    report = render(list(course_rows()))
    if args.check:
        current = Path(args.check).read_text(encoding="utf-8") if Path(args.check).is_file() else ""
        if current != report:
            print(f"{args.check} is stale; regenerate it with tools/objective_coverage.py", file=sys.stderr)
            return 1
        return 0
    sys.stdout.write(report)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
